# Generated by Django 2.2.5 on 2019-09-26 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20190816_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
