# Generated by Django 2.2.5 on 2019-09-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20190926_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên Loại')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Từ khóa loại')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Hình loại')),
                ('Image_URL', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Hình')),
            ],
            options={
                'verbose_name_plural': 'Loại Sản Phẩm',
            },
        ),
    ]
