# Generated by Django 2.2.5 on 2019-09-26 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20190926_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/', verbose_name='Banner')),
                ('Number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price_New',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá Khuyến Mãi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price_Old',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá Bán '),
        ),
        migrations.CreateModel(
            name='Image_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/', verbose_name='Hình Sản Phẩm')),
                ('Image_URL', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Hình')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
