# Generated by Django 2.2.5 on 2019-09-26 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20190926_0912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
