# Generated by Django 2.2.5 on 2019-09-26 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_Product',
        ),
    ]
