# Generated by Django 2.2.5 on 2019-09-26 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_delete_image_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/', verbose_name='Hình Sản Phẩm')),
                ('Image_URL', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Hình')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
