# Generated by Django 2.2.5 on 2019-09-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0014_auto_20190823_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa Chỉ Nhận'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Số Điện Thoại'),
        ),
    ]
